 blank_issues_enabled: false
contact_links:
  - name: Yearn Finance Community Forums and Support
    url: https://gov.yearn.finance/
    about: Please ask and answer questions here.
  - name: Yearn Finance Security & Bug Bounty
    url: https://github.com/yearn/yearn-security
    about: Please report security vulnerabilities here.
